### ISSUE TITLE
Line-wrap not working when buffer split vertically

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [joshsh/brain-mode#19] opened 2017-03-22 23:54 UTC

**Comment by joshsh** [comment] 2017-03-23 00:02
Please always include a description, including steps to reproduce the issue, even if the title seems clear.

I don't see a difference in line wrap behavior when I split the window vertically and/or horizontally.

**Comment by JeffreyBenjaminBrown** [comment] 2017-03-23 00:04
When I press ";" in move mode, if the window is split vertically, it has no effect; long lines still run off the right side of the page.

The big font I use might be part of the problem. I have the following in my .emacs file:

  (custom-set-faces
  ;; custom-set-faces was added by Custom.
   ;; If you edit it by hand, you could mess it up, so be careful.
   ;; Your init file should contain only one such instance.
   ;; If there is more than one, they won't work right.
   '(default ((t (:family "DejaVu Sans Mono" :foundry "PfEd" :slant normal :weight normal :height 200 :width normal)))))

**Comment by joshsh** [comment] 2017-04-18 05:34
I am still unable to reproduce this.  Side-by side buffers, move-mode, and toggle --> the text wraps as expected.  Did the font turn out to be a factor?

**Comment by joshsh** [comment] 2017-05-21 08:26
Closing this issue. Please re-open it if you still think it is a smsn-mode issue.

**Closed as completed by joshsh** 2017-05-21 08:26 UTC

**Comment by JeffreyBenjaminBrown** [comment] 2017-05-21 18:30
It's working for me now!
